sudo: required
dist: trusty
language: ruby
cache: bundler
rvm:
  - 2.5.3
addons:
  chrome: stable

before_script:  
  - wget -N https://chromedriver.storage.googleapis.com/73.0.3683.68/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  #- ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver
  #- export PATH="$HOME/bin:$PATH"
  #- google-chrome-stable --no-sandbox --headless --remote-debugging-port=9222 &
  - 'bundle install'

script: 
- cd youtube_test
- 'bundle exec cucumber'

branches:
  only:
    - master
       