sudo: required
language: ruby
cache: bundler

rvm:
  - 2.5.3
addons:

before_script: 
- wget https://chromedriver.storage.googleapis.com/73.0.3683.68/chromedriver_win32.zip

- unzip chromedriver_win32.zip -d /usr/local/bin/.

        - sudo chmod +x /usr/local/bin/chromedriver
        - export DISPLAY=:99.0

- 'bundle install'

script: 
- cd renfe_test
- 'bundle exec cucumber'

branches:
  only:
    - master