sudo: required
language: ruby
cache: bundler

rvm:
  - 2.5.3
addons:
  apt:
    packages:
      - chromium-chromedriver

before_script: 
- sudo apt-get update
- sudo apt-get install chromium-chromedriver
- "export PATH=$PATH:/usr/lib/chromium-browser/"
- "export DISPLAY=:99.0"
- 'bundle install'

script: 
- cd renfe_test
- 'bundle exec cucumber'

branches:
  only:
    - master