language: ruby
cache: bundler

rvm:
  - 2.5.3
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_script: 

- 'bundle install'

script: 
- cd renfe_test
- 'bundle exec cucumber'

branches:
  only:
    - master