sudo: required
dist: trusty
language: ruby
cache: bundler
rvm:
  - 2.5.3
addons:
  apt:
    packages:
      - chromium-chromedriver
before_script:  
  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver
  - 'bundle install'

script: 
- cd youtube_test
- 'bundle exec cucumber'

branches:
  only:
    - master