language: ruby
cache: bundler

rvm:
  - 2.5.3

before_script: 
- wget https://chromedriver.storage.googleapis.com/73.0.3683.68/chromedriver_win32.zip

- unzip chromedriver_win32.zip 

- export CHROME_BIN=chromium-browser
- 'bundle install'

script: 
- cd renfe_test
- 'bundle exec cucumber'

branches:
  only:
    - master