sudo: required
dist: trusty
language: ruby
cache: bundler
rvm:
  - 2.5.3
addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver
before_script:  
  - wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python2.7.12/bin/
- export CHROME_BIN=chromium-browser
  
  - 'bundle install'

script: 
- cd youtube_test
- 'bundle exec cucumber'

branches:
  only:
    - master
       