sudo: required
dist: trusty
language: ruby

rvm:
  - 2.5.3
addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver
before_script:  
  #- ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver
  #- export PATH="$HOME/bin:$PATH"
  - export PATH=$PATH:/usr/lib/chromium-browser/
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  #- google-chrome-stable --no-sandbox  &
  - 'bundle install'

script: 
- cd renfe_test
- 'bundle exec cucumber'
#- cd ..
#- cd youtube_test
#- 'bundle exec cucumber' 

branches:
  only:
    - master
       
    